
package cz.sa.dovolena.server.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimilarityQueueServiceImplService", targetNamespace = "http://ws.server.dovolena.sa.cz/", wsdlLocation = "http://127.0.0.1:8080/Dovolena/services/similarity/")
public class SimilarityQueueServiceImplService
    extends Service
{

    private final static URL SIMILARITYQUEUESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMILARITYQUEUESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName SIMILARITYQUEUESERVICEIMPLSERVICE_QNAME = new QName("http://ws.server.dovolena.sa.cz/", "SimilarityQueueServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/Dovolena/services/similarity/");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMILARITYQUEUESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        SIMILARITYQUEUESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public SimilarityQueueServiceImplService() {
        super(__getWsdlLocation(), SIMILARITYQUEUESERVICEIMPLSERVICE_QNAME);
    }

    public SimilarityQueueServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMILARITYQUEUESERVICEIMPLSERVICE_QNAME, features);
    }

    public SimilarityQueueServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SIMILARITYQUEUESERVICEIMPLSERVICE_QNAME);
    }

    public SimilarityQueueServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMILARITYQUEUESERVICEIMPLSERVICE_QNAME, features);
    }

    public SimilarityQueueServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimilarityQueueServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimilarityQueueService
     */
    @WebEndpoint(name = "SimilarityQueueServiceImplPort")
    public SimilarityQueueService getSimilarityQueueServiceImplPort() {
        return super.getPort(new QName("http://ws.server.dovolena.sa.cz/", "SimilarityQueueServiceImplPort"), SimilarityQueueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimilarityQueueService
     */
    @WebEndpoint(name = "SimilarityQueueServiceImplPort")
    public SimilarityQueueService getSimilarityQueueServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.server.dovolena.sa.cz/", "SimilarityQueueServiceImplPort"), SimilarityQueueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMILARITYQUEUESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw SIMILARITYQUEUESERVICEIMPLSERVICE_EXCEPTION;
        }
        return SIMILARITYQUEUESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
